### ISSUE TITLE
Falta un miembro del equipo

### ISSUE THREAD

**Issue by MPerezMateo** [aigora/twA109-david-alvaro-ignacio#1]
Falta Alvaro por unirse, debe hacerlo mediante moodle en el apartado Trabajos de Equipo para que los profes le puedan ver y corregir.

**Comment by Juliauru** [comment]
Hay un compañero que aún no ha entrado a AIGORA y se acaba el tiempo. Esta semana se acaba el plazo para registrarse, y si no está no podrá ser evaulado del trabajo.

**Comment by Juliauru** [comment]
Ya estáis todos!
